name: Build Blackbox Exporter

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 选择合适的 Go 版本
              
      - name: Clear existing cache
      run: rm -rf ~/.cache/go-build ~/go/pkg/mod

      - name: 编译 Blackbox Exporter
        run: |
          make build
          ls -lah blackbox_exporter

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: blackbox_exporter_binary
          path: blackbox_exporter
